spring:
  datasource:
    url: jdbc:mysql://localhost:3001/pcbs_core_db?connectionTimeZone=Asia/Jakarta
    username: root
    password: t2zQ18BX!6y4
  jpa:
    hibernate:
      ddl-auto: update

client:
  datasharedCore:
    baseUrl: http://localhost:18030/core-data-shared

logging:
  #  pattern:
  #    console: "%clr(%X{CorrelationId}){yellow} %clr(%X{username}){yellow} | %clr(%-5p) | %clr(%d{yyyy-MM-dd E HH:mm:ss.SSS}){blue} | %clr(${PID}){faint} | %clr([%t]){cyan} | %class{36}.%M %L | %clr(%msg){green} %n"
  file:
    name: ./logs/pcbs-settlement-file-download.log
#  level:
#    root: debug